### ISSUE TITLE
Plural forms for "free searches remaining"

### ISSUE THREAD

**Issue by zemlanin** [cliss/callsheet-localizations#11]
`%lld free search%@ remaining` would be translated differently depending on `%lld`'s value

The ID should probably be `%lld free searches remaining|==|plural.XXX`?

**Comment by DonSqueak** [comment]
Yup, encountered this in my pass as well.

**Comment by zemlanin** [comment]
https://github.com/cliss/callsheet-localizations/commit/811df129e3b508eea0c0b9b8ed03622343f02918
