### ISSUE TITLE
The Italian translation needs some extra work, and there are a few issues with number values

### ISSUE THREAD

**Issue by cdf1982** [cliss/callsheet-localizations#117]
I'm opening this just to let @cliss know that testing the localized app that's now live in the App Store made evident that some translations to Italian can be improved.
I will work on them as soon as I have a moment and open a PR.

A couple more things:

1. Years, duration and episodes numbers do not seem to be shown! I only see the labels:

![image](https://github.com/cliss/callsheet-localizations/assets/11062186/d27b01fe-106a-44ab-9c14-66610cdc8daa)
![image](https://github.com/cliss/callsheet-localizations/assets/11062186/1fc09e4a-60ce-4a07-9c5a-08de76b0123a)
![image](https://github.com/cliss/callsheet-localizations/assets/11062186/4b15abd3-3b75-4a3a-83c0-767e1acc62a5)

2. The About screen has most of the text not translated:
![image](https://github.com/cliss/callsheet-localizations/assets/11062186/3f194b97-23ae-43a4-95d4-efa4427d762e)

3. These labels are truncated instead of wrapping:
![image](https://github.com/cliss/callsheet-localizations/assets/11062186/fc95cccd-d8a6-4e60-af6d-b61a8daaecd8)

**Comment by cliss** [comment]
Some of these were fixed in a beta release I just sent through; more will be fixed in the next one. Thanks!!

**Comment by cdf1982** [comment]
I have opened a [PR](https://github.com/cliss/callsheet-localizations/pull/119) for the aforementioned improvements to the Italian localization.

It's likely that you've also already catched a few missing localisation to the upsell screen, but here's what I've noticed anyway:
![IMG_4830](https://github.com/cliss/callsheet-localizations/assets/11062186/5e17af62-7a07-4f20-9e72-a4cc441c429f)
![IMG_4831](https://github.com/cliss/callsheet-localizations/assets/11062186/5d12ec35-d4a4-4add-ad5f-b9a0481c1792)
![IMG_4835](https://github.com/cliss/callsheet-localizations/assets/11062186/b0afe819-ecad-40e7-863b-5ac66746e985)

And by the way, if you think it can help to double-check the betas and you have a TF link, I won't say no :)

**Comment by cliss** [comment]
@cdf1982 If you're not already on the TestFlight, please either [reach out on Mastodon](https://mastodon.social/@caseyliss) or [email](https://www.caseyliss.com/contact) and let me know where to send the invite email. :)
