### ISSUE TITLE
"Awards" localization

### ISSUE THREAD

**Issue by zemlanin** [cliss/callsheet-localizations#140]
Less of an issue, more of a question

Latest TestFlight build has new "Awards" quick access link. I can't find any mentions of this string it in this repo, but it is translated (correctly, at least to Ukrainian)

Is it some automatic thing?

**Comment by cliss** [comment]
Since it was just one item, I just did it using ChatGPT. 😇 

That reminds me, though, that I need to update this repo. Thanks!

**Comment by cliss** [comment]
dc926169351e32663b1667ccc5600f11bef86978
