### ISSUE TITLE
Add App Store localizations

### ISSUE THREAD

**Issue by cliss** [cliss/callsheet-localizations#21]
@cliss personally, I'd wouldn't mind helping with the description, if you decide to pull the trigger. And I'm sure others would love to help too for their languages.
Txt files is a reasonable way to go, IMHO, and indeed I've seen that method used in the past by other apps.

_Originally posted by @cdf1982 in https://github.com/cliss/callsheet-localizations/issues/18#issuecomment-2110049202_

**Comment by sayrer** [comment]
You can update these in the API too. I've never done it myself, but I know folks who've done it.

https://developer.apple.com/documentation/appstoreconnectapi/app_store/app_metadata/app_info_localizations

**Comment by cliss** [comment]
Taken care of by hand. 👍🏻
