### ISSUE TITLE
Add IAP translations to App Store Connect

### ISSUE THREAD

**Issue by cliss** [cliss/callsheet-localizations#23]
https://github.com/cliss/callsheet-localizations/pull/22#issuecomment-2111046988

**Comment by DonSqueak** [comment]
> [#22 (comment)](https://github.com/cliss/callsheet-localizations/pull/22#issuecomment-2111046988)

> Actually re: the IAP stuff, you very well may have translated them, but that has to go into Apple's backend, which I haven't done yet. 🤪

So, I have indeed translated the stuff you show in the screenshot.
I don't see:
* Yearly Subscription (I do see "Yearly", but Subscription and the Save 17 % part is missing)
* where "per monat" and "per jahr" came from, as these are not in the file (and are wrong ;) )

**Comment by cliss** [comment]
Fixed in a842ccf
