### ISSUE TITLE
Potentially Split Up Two Incongruent Uses of "Known for"?

### ISSUE THREAD

**Issue by cliss** [cliss/callsheet-localizations#55]
https://github.com/cliss/callsheet-localizations/pull/46#discussion_r1611940712

@cliss: Perhaps use two different keys and make sure the English localization handles them properly?

**Comment by cliss** [comment]
@DonSqueak Can you explain a little better so I understand, please?

There are two different places I use the exact string `Known For`:

* A person is "Known For Directing/Acting/etc"
* In the Persnickety Preferences, meaning "Show me a list of stuff this person is in yes/no"

You're saying German would prefer different translations for these two?

**Comment by DonSqueak** [comment]
Ideally yes.

- A person is "Known For Directing/Acting/etc" --> `Bekannt für`
- In the Persnickety Preferences, meaning "Show me a list of stuff this person is in yes/no" --> `Bekannt aus` or `Man kennt sie aus`

The second of the two, when left as `Bekannt für` sounds a bit... wonky.

**Comment by cliss** [comment]
Added in 3070201b84dd729ba9a4f090a709de4af9898c22.

For every language that had a translation for `Known For`, I copied the one that pre-existed. May be worth a second look though.

**Comment by DonSqueak** [comment]
Solved! Thank you!
