### ISSUE TITLE
Ready for RTL scripts?

### ISSUE THREAD

**Issue by sayrer** [cliss/callsheet-localizations#57]
Arabic, Hebrew, and Farsi will require you to change the direction of your app. So, something that's in the left corner would be in the right corner for these. I am sure Swift UI makes this a little bit easier than it used to be, but there will be lots of little layout details to fix. It's like hunting down strings, but for coordinates.

Meaning: try these in round 2, once you work out German, Spanish, etc

**Comment by cliss** [comment]
Should be taken care of automagically; I'll reopen this (or please do so yourself!) if you see issues!
