### ISSUE TITLE
Missing strings in subscription management

### ISSUE THREAD

**Issue by technocidal** [cliss/callsheet-localizations#69]
The description that shows up when a subscription lapsed is currently not part of the localisation files and if possible, this should also use the localised display name for the IAP.

![IMG_2523](https://github.com/cliss/callsheet-localizations/assets/14994778/f4265efe-7f03-4fb1-9ecd-318cbe0621fd)

**Comment by cliss** [comment]
Added in 8e9c3c4.

Sorry, @DonSqueak, @technocidal, @fweber-de, @orisraeli, @zemlanin, @spitfire, @Deddiekoel, @icod, @cdf1982, @apfernandes, @gkeep, @unaiherran, @sebdanielsson, @EricEEEEE, @SamTheGeek, @lognseth, @kenroy, @jaddkeita, @Hanse00 

😇 🫣 😬
