### ISSUE TITLE
Spanish MX

### ISSUE THREAD

**Issue by ccavazos** [cliss/callsheet-localizations#98]
Hey @cliss - I'll be happy to take a pass at `es-MX` to expand on the default `es-ES` that @unaiherran helped with.

**Comment by cliss** [comment]
I'd love that! Added in a9e2d55dede6b55e5d484465c14d1f328590ad8d; I copied the existing Spanish translation.

**Comment by sayrer** [comment]
Depending on what @ccavazos wants to do, you might be able to use it as es-419 (Spanish - Latin America). It's definitely possible to specialize it to es-MX and es-AR, though.

**Comment by cliss** [comment]
Yeah, I can switch from `es-MX` → `es-419` if that's what @ccavazos is after. Y'all tell me! 😄

**Comment by sayrer** [comment]
For context, it usually goes this way for a Mexican user: 'es-MX' if available, then 'es-419' if available, then 'es-es'.

**Comment by unaiherran** [comment]
And please, if you find any typo tell me. I have checked and rechecked... but I know for sure one will surface just when it's  released.

**Comment by ccavazos** [comment]
Hello all! I have submitted a PR with the `es-MX` translation done to the best of my abilities. https://github.com/cliss/callsheet-localizations/pull/112 

@unaiherran you did a great job and it helped me a lot to get started! I did find a few typos and I did my best to fix them. 

@sayrer is right that the way the localization will cascade for a MX user is going to be es-MX -> es-419 -> es-ES so for them is not really going to be any different. The value of creating es-419 will be for Latin-America (but non Mexico) users to see the MX version instead of the ES version.

I do _believe_ that es-MX will be closer to Latin-American Spanish than es-ES but I'm not an expert on non es-MX languages to be 100 sure.

My recommendation for @cliss would be:
- Once merged, copy es-MX and create es-419 as a copy of that.
- Depending on your analytics on who's downloading the app, if it's a substancial number and if you can share the top 3 countries, ping me and I'll be happy to do some research on idioms to better translate to those users because who are we kidding... everybody must have Callsheet in their language! 🖖 

Also, if the PR is merged, feel free to close this issue 😃

**Comment by sayrer** [comment]
I think the film/tv words will be about the same except for Argentina/Uruguay: [RioPlatense](https://en.wikipedia.org/wiki/Rioplatense_Spanish). Less sure of the billing/subscription words.

I'm not that great at speaking Spanish, but I can hear it well. It varies from Chile to Mexico, but I can hear all of that. Argentina/Uruguay are a lot tougher, because it's the small words that vary, like "re" instead of "mui" etc.

**Comment by cliss** [comment]
@ccavazos -419 added in ff8d87ee62cd9ffac0c1f92672b5827f7186ce75; please take a look at your convenience!

(cc @sayrer)

**Comment by sayrer** [comment]
I always ask a question about -419 dialects if I have the chance, and everyone says Peruvian is the one everyone understands (or, "most neutral"). Even if it is not super local, it will be understandable. But I think it will just be a few words changed from es-MX in this app.

**Comment by ccavazos** [comment]
@cliss I couldn't find any meaningful differences for this file. To the best of my knowledge I think is safe for you to include 419 and if you hear any feedback from latin American non-mexican users you can always reach out to me and I'll be happy to help.
